# Generated by Django 6.0 on 2025-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок книги')),
                ('year', models.IntegerField(max_length=4, verbose_name='Год выпуска')),
                ('category', models.CharField(max_length=100, verbose_name='Категория книги')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр книги')),
                ('publisher', models.CharField(max_length=100, verbose_name='Издатель книги')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Обложка книги')),
                ('text', models.FileField(upload_to='books', verbose_name='Файл с книгой')),
                ('authors', models.ManyToManyField(to='api.author', verbose_name='Автор книги')),
            ],
        ),
    ]
